version: '2'

services:
    web:
        image: lavoweb/php-8.1
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - lamp_httpd_cfg:/etc/apache2/sites-enabled
            - lamp_httpd_ssl:/opt/ssl
            - lamp_httpd_www:/var/www/html
        environment:
            - ALLOW_OVERRIDE=true
        links:
            - db:db
        networks:
            backend:
                ipv4_address: 192.168.10.50

    db:
        image: mysql:latest
        volumes:
            - lamp_mysql_db:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: 123
        networks:
            backend:

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
        networks:
            backend:

volumes:
    lamp_httpd_cfg:
        driver_opts:
            type: none
            device: "./data/cfg"
            o: bind
    lamp_httpd_ssl:
        driver_opts:
            type: none
            device: "./data/ssl"
            o: bind
    lamp_httpd_www:
        driver_opts:
            type: none
            device: "./data/www"
            o: bind
    lamp_mysql_db:
        driver_opts:
            type: none
            device: "./data/db"
            o: bind

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24