version: '2'

services:
    web:
        image: lavoweb/php-8.1
        ports:
            - "80:80"
        volumes:
            - lampwww:/var/www/html
        links:
            - db:db
        networks:
            backend:
                ipv4_address: 192.168.10.50

    db:
        image: mysql:latest
        volumes:
            - lampdb:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: 123
        networks:
            backend:

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
        networks:
            backend:

volumes:
    lampwww:
        driver_opts:
            type: none
            device: "./data/www"
            o: bind
    lampdb:
        driver_opts:
            type: none
            device: "./data/db"
            o: bind

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24